version: '3.1'
services:
  wserver:
    build: ./server
    ports:
      - 8000:8000
    volumes:
      - ./server:/home/server:delegated
    restart: "always"

  db:
    image: postgres:12.2
    build: ./postgres/
    ports:
      - 5432:5432
    volumes:
      - ./postgres/volumes/data:/var/lib/postgresql/data:delegated